modLoader = "javafml"
loaderVersion = "[43,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/GrowthcraftCE/Growthcraft-Trapper/issues"

[[mods]]
modId = "growthcraft_trapper"
version = "8.0.0"
displayName = "Growthcraft Trapper"
updateJSONURL = "https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-Updates/master/growthcraft-trapper-versions.json"
displayURL = "https://github.com/GrowthcraftCE/Growthcraft-Trapper/wiki"
logoFile = "growthcraft_trapper_logo.png"
credits = "Thanks to Gwafu for starting a great mod. And the Growthcraft CE Development for continuing the work."
authors = "Alatyami"
description = '''Growtchraft Trapper is a realistic and immersive Forge mod that adds various new trapping elements to the game of Minecraft.
    '''

[[dependencies.growthcraft_trapper]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.growthcraft_trapper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"